### ISSUE TITLE
$client->setStreamResult Not working on OSX

### ISSUE THREAD

**Issue by tieutantan** [KhristenkoYura/mcurl#4]
Hi, 

On Osx when use function `setStreamResult `

`$client->setStreamResult(Client::STREAM_FILE);` or set `Client::STREAM_MEMORY`

All data result return is empty, checked [$result->httpCode](url) return 200, all it's ok, no error, but nothing return. Please fix it, thank you.

**Comment by KhristenkoYura** [comment]
How version php you are using?

**Comment by tieutantan** [comment]
Run on Ampps with PHP 7.0.10 all default setting, Osx 10.12.2.

**Comment by KhristenkoYura** [comment]
Sorry, I have no MacBook to check.
Most likely you have a problem with php, not the library.
Run this:
```
<?php
$fp = fopen('php://memory', 'r+');
fwrite($fp, 'qwerty');
rewind($fp);
echo fread($fp, strlen('qwerty'));
fclose($fp);
```

**Comment by KhristenkoYura** [comment]
And what return: $result->getHeaders() ?
